### ISSUE TITLE
v1.7.3-9.RC-1的配置文件新结构大改

### ISSUE THREAD

**Issue by 8MiYile** [LiterMC/go-openbmclapi#18]
我是测试完毕后回滚还原配置文件还是什么

**Comment by zyxkad** [comment]
啊对，是得会滚配置文件

**Comment by 8MiYile** [comment]
我以为你会发个Stable呢。。。好 等会我自己降级版本吧

**Comment by 8MiYile** [comment]
那个 有没有dav的连接信息调用的方法 就是 你要用这个结构的话 我觉得得添加个 webdav配置列表

**Comment by zyxkad** [comment]
目前打算把username/password放到data内，也可能另外创建一个option把这些username/password整一块，然后把id放到data里面，避免多次输入相同密码

**Comment by 8MiYile** [comment]
直接这样
```yaml
webdav-config:
  - name: "8Mi-HomeWLAN.AList"
    url: "http://127.0.0.1:5299/dav"
    user: ""
    pass: ""
```
