### ISSUE TITLE
tunneler 功能配置问题

### ISSUE THREAD

**Issue by ApliNi** [LiterMC/go-openbmclapi#63]
您好, 我尝试启用 tunneler 功能时遇到问题, 即使使用默认的正则表达式也无法启动:

```yaml
tunneler:
  enable: true
  tunnel-program: ./addr.cmd
  output-regex: (?<host>.+):(?<port>\d+)
  tunnel-timeout: 0
```

```
Go-OpenBmclAPI  Copyright (C) 2023 Kevin Z <zyxkad@gmail.com>
This program comes with ABSOLUTELY NO WARRANTY;
This is free software, and you are welcome to redistribute it under certain conditions;
Use subcommand 'license' for more information

[ERRO][21:38:55]: 无法解析配置文件: error parsing regexp: invalid or unsupported Perl syntax: `(?<`
[ERRO][21:38:55]: 节点正在退出, 代码 1
[ERRO][21:38:55]: 请在提交问题前阅读 https://github.com/LiterMC/go-openbmclapi?tab=readme-ov-file#faq
[WARN][21:38:55]: 检测到您是新手 Windows 用户. 我们正在帮助您打开浏览器 ...
```
